apiVersion: v1
kind: Service
metadata:
  name: postgres  # 👈 This becomes the DNS name! Other pods use "postgres" to connect
  labels:
    app: postgres
spec:
  type: ClusterIP  # 👈 Internal only - we don't need external access to our DB
  selector:
    app: postgres  # 👈 This matches our Deployment's labels
  ports:
  - port: 5432  # 👈 The port other services will use
    targetPort: 5432  # 👈 The port on the pod (where PostgreSQL is listening)
    name: postgres